name: CI
on: [ push, pull_request ]
jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      # --------- Setup steps ---------
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          php-version: "8.4"
          ini-values: memory_limit=-1
          extensions: pcov, xdebug, sodium, fileinfo

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2

      # --------- Run steps ---------
      - name: "Unit Tests"
        run: "vendor/bin/phpunit"

#      - name: "Static code analysis"
#        run: "vendor/bin/psalm"